### ISSUE TITLE
[BUG] Unable to use FTA Error = save config to File - FTAnalyzer on Windows 10

### ISSUE THREAD

**Issue by mjsarl** [ShammyLevva/FTAnalyzer#190]
**Version Number problem appears in** = 8.0.1.0

**Describe the bug**
Any attempt to load GED file appears to process file properly but then an error dialogue is displayed which indicates that FTA was unable to save config to file.
The same error message is shown with any attempt to navigate the application menus

![2020-10-31](https://user-images.githubusercontent.com/2650258/97782990-b3bfe080-1b8c-11eb-9983-ab2a20ee2e7e.png)
**Screenshots**

**Additional context**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Configuration.ConfigurationErrorsException: Unable to save config to file 'C:\Users\marks\AppData\Local\FTAnalyzer\FTAnalyzer.exe_Url_tnwwguqoexxm1gixxujmrmkn1cyayjuy\1.0.0.0\user.config'.
   at System.Configuration.Internal.WriteFileContext.ReplaceFile(String Source, String Target)
   at System.Configuration.Internal.WriteFileContext.Complete(String filename, Boolean success)
   at System.Configuration.Internal.InternalConfigHost.StaticWriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.UpdateConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)

**Comment by ShammyLevva** [comment]
This is the Microsoft Store screwing up the install. Basically it’s installed the app but hasn’t allowed you the permissions to save configuration options. 

I’ve yet to understand how this happens but it’s related to how the installer fails to set permissions. Unfortunately I cannot do anything in the program to fix this bug as it’s in the a Microsoft installer. The only fix is to use the alternative installer at www.ftanalyzer.com/releases
