### ISSUE TITLE
FT Analyzer 6.4.1.0 - Cannot Start Application

### ISSUE THREAD

**Issue by BobWhaley** [ShammyLevva/FTAnalyzer#26]
Attempting to download and install this version of FT Analyzer results in a 'Cannot Start Application' messagebox.

The details associated with this messagebox are shown below:
===============================================================
PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2633.0 built by: NET471REL1LAST_C
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: http://ftanalyzer.com/install/FTAnalyzer.application
						Server		: GitHub.com

IDENTITIES
	Deployment Identity		: FTAnalyzer.application, Version=6.4.1.0, Culture=en, PublicKeyToken=c7ce9728f49d2c1c, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://ftanalyzer.com/install/FTAnalyzer.application resulted in exception. Following failure messages were detected:
		+ Activation failed.
		+ Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [17/04/2018 22:41:25] : Activation of http://ftanalyzer.com/install/FTAnalyzer.application has started.
	* [17/04/2018 22:41:25] : Processing of deployment manifest has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [17/04/2018 22:41:33] System.Deployment.Application.DeploymentException (Activation)
		- Activation failed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.UnauthorizedAccessException
		- Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [17/04/2018 22:41:25]
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0

**Comment by ShammyLevva** [comment]
The error is saying

Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Which suggests the account you re using doesn’t have permission to install the app, or you didn’t allow it to install. Can you retry and ensure you check to allow the install if it asks are you sure you want to trust the install or similar wording. Alternatively run the install as administrator to ensure it has permissions to install.

**Comment by ShammyLevva** [comment]
User reported issue fixed.
