### ISSUE TITLE
FTAnalyser Cannot be downloaded

### ISSUE THREAD

**Issue by mollcons** [ShammyLevva/FTAnalyzer#31]
Apparently the files are "Corrupt in deployment"

Here is the complete detail:
PLATFORM VERSION INFO
	Windows 			: 10.0.17134.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3056.0 built by: NET472REL1
	clr.dll 			: 4.7.3131.0 built by: NET472REL1LAST
	dfdll.dll 			: 4.7.3056.0 built by: NET472REL1
	dfshim.dll 			: 10.0.17134.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: http://ftanalyzer.com/install/FTAnalyzer.application
						Server		: GitHub.com
	Deployment Provider url		: http://ftanalyzer.com/install/FTAnalyzer.application
	Application url			: http://ftanalyzer.com/install/Application%20Files/FTAnalyzer_6_4_3_1/FTAnalyzer.exe.manifest
						Server		: GitHub.com

IDENTITIES
	Deployment Identity		: FTAnalyzer.application, Version=6.4.3.1, Culture=en, PublicKeyToken=c7ce9728f49d2c1c, processorArchitecture=msil
	Application Identity		: FTAnalyzer.exe, Version=6.4.3.1, Culture=en, PublicKeyToken=c7ce9728f49d2c1c, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://ftanalyzer.com/install/FTAnalyzer.application resulted in exception. Following failure messages were detected:
		+ Exception occurred loading manifest from file FTAnalyzer.exe: the manifest may not be valid or the file could not be opened. 
		+ File FTAnalyzer.exe is not a valid Portable Executable (PE) file.
		+ PE file does not have enough data.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [13/07/2018 18:09:58] : Activation of http://ftanalyzer.com/install/FTAnalyzer.application has started.
	* [13/07/2018 18:10:00] : Processing of deployment manifest has successfully completed.
	* [13/07/2018 18:10:00] : Installation of the application has started.
	* [13/07/2018 18:10:01] : Processing of application manifest has successfully completed.
	* [13/07/2018 18:10:03] : Found compatible runtime version 4.0.30319.
	* [13/07/2018 18:10:03] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [13/07/2018 18:36:19] System.Deployment.Application.InvalidDeploymentException (ManifestLoad)
		- Exception occurred loading manifest from file FTAnalyzer.exe: the manifest may not be valid or the file could not be opened. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ManifestLoadExceptionHelper(Exception exception, String filePath)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromInternalManifestFile(String filePath)
			at System.Deployment.Application.DownloadManager.ProcessDownloadedFile(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.DownloadModifiedEventHandler.Invoke(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.OnModified()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.IO.IOException
		- File FTAnalyzer.exe is not a valid Portable Executable (PE) file.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.PEStream.ConstructFromFile(String filePath, Boolean partialConstruct)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromInternalManifestFile(String filePath)
		--- Inner Exception ---
		System.IO.IOException
		- PE file does not have enough data.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.PEStream.PEComponent.ReadData(FileStream file, Int64 position, Type dataType)
			at System.Deployment.Application.PEStream.ResourceDirectory..ctor(ResourceSection resourceSection, FileStream file, Int64 rootResourceAddress, Int64 resourceAddress, Int64 addressDelta, Boolean partialConstruct)
			at System.Deployment.Application.PEStream.ResourceSection..ctor(FileStream file, SectionHeader sectionHeader, Boolean partialConstruct)
			at System.Deployment.Application.PEStream.ConstructPEImage(FileStream file, Boolean partialConstruct)
			at System.Deployment.Application.PEStream.ConstructFromFile(String filePath, Boolean partialConstruct)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by ShammyLevva** [comment]
Strange it may need to be re:Downloaded. I’ve updated a new version as v6.5.0.0 which may fix the issue.

**Comment by ShammyLevva** [comment]
No further feedback from user.
