### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by cjades** [ShammyLevva/FTAnalyzer#64]
**Describe the bug**
Unhandled exception

**To Reproduce**
1. Go to 'Maps'
2. Click on 'Show Timeline'
4. See error as per image

**Expected behavior**

**Screenshots**
Attached
![timeline](https://user-images.githubusercontent.com/45994652/50310136-fe547a00-0498-11e9-8d07-497a061d9e05.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Quantum 64

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ShammyLevva** [comment]
Sorry don't understand what you mean in step 3. Scroll down to '...' I can't see a ... on screen.

**Comment by ShammyLevva** [comment]
Note that the first block of contents of the details window provides me with invaluable information on what the program was doing at the time of the issue. So including that helps a lot.

**Comment by cjades** [comment]
[Have updated FT since report] but still receive this: Hope it's enough.

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at FTAnalyzer.Forms.TimeLine.SetOpacity()
   at FTAnalyzer.Forms.TimeLine.SetupMap()
   at FTAnalyzer.Forms.TimeLine.TimeLine_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ShammyLevva** [comment]
Yup that helped a lot I've added in a check to see if the value is out of range before setting it. Fixed for v7.2.1.2
