### ISSUE TITLE
the  application is missing required files

### ISSUE THREAD

**Issue by qgenesist** [ShammyLevva/FTAnalyzer#7]
when I send the error to the deployment server it opens a tab per word telling me the %number%number so on is not found.

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2114.0 built by: NET47REL1LAST
	clr.dll 			: 4.7.2114.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2114.0 built by: NET47REL1LAST
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: http://ftanalyzer.com/install/FTAnalyzer.application
						Server		: GitHub.com
	Deployment Provider url		: http://ftanalyzer.com/install/FTAnalyzer.application
	Application url			: http://ftanalyzer.com/install/Application%20Files/FTAnalyzer_6_0_0_0/FTAnalyzer.exe.manifest
						Server		: GitHub.com

IDENTITIES
	Deployment Identity		: FTAnalyzer.application, Version=6.0.0.0, Culture=en, PublicKeyToken=c7ce9728f49d2c1c, processorArchitecture=msil
	Application Identity		: FTAnalyzer.exe, Version=6.0.0.0, Culture=en, PublicKeyToken=c7ce9728f49d2c1c, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://ftanalyzer.com/install/FTAnalyzer.application resulted in exception. Following failure messages were detected:
		+ Downloading http://ftanalyzer.com/install/Application Files/FTAnalyzer_6_0_0_0/x64/gdal_wrap.dll.deploy did not succeed.
		+ The remote server returned an error: (404) Not Found.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [9/17/2017 5:56:07 AM] : Activation of http://ftanalyzer.com/install/FTAnalyzer.application has started.
	* [9/17/2017 5:56:08 AM] : Processing of deployment manifest has successfully completed.
	* [9/17/2017 5:56:08 AM] : Installation of the application has started.
	* [9/17/2017 5:56:08 AM] : Processing of application manifest has successfully completed.
	* [9/17/2017 5:56:12 AM] : Found compatible runtime version 4.0.30319.
	* [9/17/2017 5:56:12 AM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [9/17/2017 5:56:13 AM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://ftanalyzer.com/install/Application Files/FTAnalyzer_6_0_0_0/x64/gdal_wrap.dll.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (404) Not Found.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by ShammyLevva** [comment]
hmmm not sure why I didn't get email alerting me to this issue. I'll have a look over next few days.

**Comment by ShammyLevva** [comment]
Fixed in v6.0.1.0 install from http://ftanalyzer.com/install
